- hosts: localhost
  remote_user: root
  gather_facts: no
  vars:
    YOUR_CLOUDFLARE_EMAIL: ''
    YOUR_CLOUDFLARE_API_KEY: ''
    YOUR_DNS_ZONE: ''
  tasks:
    - name: Create OnApp VS
      onapp_vs:
        name: 'ansible_module_test'
        hostname: 'ansiblemoduletest'
        new: true
        memory: 1024
        cpus: 1
        template_id: <your-template-id>
        primary_disk_size: 10
        primary_network_id: <your-network-id>
        primary_network_group_id: <your-network-group-id>
        labels:
          stack: kubernetes
          layer: master
          environment: test
      register: result
    - name: Register new VS with CloudFlare DNS
      cloudflare_dns:
        zone: "{{ YOUR_DNS_ZONE }}"
        record: "{{ result.hostname }}.afs"
        type: A
        value: "{{ result.public_ips|first }}"
        account_email: "{{ YOUR_CLOUDFLARE_EMAIL }}"
        account_api_token: "{{ YOUR_CLOUDFLARE_API_KEY }}"
      register: record
    - debug: var=result
